### ISSUE TITLE
Skipped test groups digests and certificate for spdm version 1.0/1.1

### ISSUE THREAD

**Issue by Dhruva21** [DMTF/SPDM-Responder-Validator#102]
I ran spdm_validator_sample exe against our Drive(spdm version 1.0 and 1.1 supported). I observed the test group digests and test group certificate are skipped and rest of test groups are running perfect.

Here is the skipped test groups result test log.
![image](https://github.com/DMTF/SPDM-Responder-Validator/assets/54857981/d884789c-a277-4ef6-973c-12821f3dc4ae)

When I looked into the code, I observed: 
Host sends capability command with 1.2 version, but device doesn’t support it. So this test is failed, but it already has overwritten the requester’s version. After that, requester tries to establish new connection by get version however there is only 1.2 version in context.

Made changes in 
1. spdm_test_case_certificate_setup_version_any 
2. spdm_test_case_digests_setup_version_any
![image](https://github.com/DMTF/SPDM-Responder-Validator/assets/54857981/f24c4f98-ee4f-4d9e-89a7-648724de3ca4)

After this change I was successfully able to run all the test groups.

**Comment by jyao1** [comment]
I found the root-cause.

Although we have `case_teardown_func()` to restore the environment, there might be case that `case_setup_func()` returns failure then **the `case_teardown_func()` is skipped.**. Then the spdm_version count is NOT restored.

I think `common_test_run_test_suite()` should be fixed to handle that case.

**Comment by Dhruva21** [comment]
@jyao1 , this issue has been resolved with your changes in #104 .
