### ISSUE TITLE
MEASUREMENTS fail for all slot id except for 0 (GROUP 7 TC) 

### ISSUE THREAD

**Issue by chanss-park** [DMTF/SPDM-Responder-Validator#122]
In GROUP 7 TC (spdm_responder_test_7_measurements.c),
only one certificate chain with slot 0 is set on setup phase.
This causes MEASUREMENTS fail for all slot id except for 0.

**Comment by jyao1** [comment]
@chanss-park, all slots are using same key. I am not sure why it fails.

Are you observing the failure? If so, please let me know how to reproduce.
or just guessing that it will failure?

**Comment by chanss-park** [comment]
(Following the comment on #121)
Is it also intended to use only slot 0 in TC 6.2 ? (VCA then CHALLENGE without GET_DIGEST and GET_CERTIFICATE)
In the TC above, 
"spdm_context->connection_info.peer_used_cert_chain_slot_id" is always 0 at line 568 
as the first argument of libspdm_verify_challenge_auth_signature().
Please confirm.
