### ISSUE TITLE
Version.InvalidRequest test expectations are inaccurate

### ISSUE THREAD

**Issue by okt-olgak** [DMTF/SPDM-Responder-Validator#124]
We have stumbled upon this while running SPDM-Reponder-Validator tests standalone, without the spdm-emu infra.

The current test case is:

>    Requester -> GET_VERSION {SPDMVersion=0x11, Param1=0, Param2=0}
>    SpdmMessage <- Responder
>
>Assertion 1.2.1: sizeof(SpdmMessage) >= sizeof(ERROR)
>
>Assertion 1.2.2: SpdmMessage.RequestResponseCode == ERROR
>
>Assertion 1.2.3: SpdmMessage.SPDMVersion == 0x10
>[...]

Assertion 1.2.3 is inaccurate - this is only guaranteed to happen if this happens pre-VCA (or post-successful GET_VERSION). Post-VCA this error can return the negotiated SPDM version.

**Comment by steven-bellock** [comment]
I'll ask the SPDM WG if the above text should be back-ported to the 1.0/1.1 specifications.

**Comment by okt-olgak** [comment]
> The ERROR message resulting from an invalid GET_VERSION request shall have the value of the SPDMVersion field set to 0x10

oh, you're right! did not notice this in the specification.

**Comment by steven-bellock** [comment]
@jyao1 to remove the test. I'll file an issue with the SPDM Working Group to bring visibility.
