### ISSUE TITLE
Plan to support SPDM 1.3

### ISSUE THREAD

**Issue by rw8896** [DMTF/SPDM-Responder-Validator#130]
Hi,

I am not sure about the release plan to update/add test cases for 1.3 specific changes.
But it probably shouldn't fail all the responder claiming to support SPDM 1.3?

https://github.com/DMTF/SPDM-Responder-Validator/blob/34c02216f43e50c06615ab9958b8e590b2d0e574/library/spdm_responder_conformance_test_lib/spdm_responder_test_1_version.c#L102-L114

**Comment by steven-bellock** [comment]
@rw8896 that is on the schedule (not sure when) but we are focused on adding 1.3 functionality to libspdm first.

**Comment by rw8896** [comment]
Got it, thanks!
