### ISSUE TITLE
'spdm_request_size' is assigned, but that stored value is overwritten before it can be used

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/SPDM-Responder-Validator#16]
`spdm_request_size` may be assigned on line 956 or line 959 or line 962, but `spdm_request_size` is reassigned on line 967
https://github.com/DMTF/SPDM-Responder-Validator/blob/61debbcffb1cd240f2908aee95ead1a974272322/library/spdm_responder_conformance_test_lib/spdm_responder_test_2_capabilities.c#L954-L968

**Comment by jyao1** [comment]
line 967 should be removed.
