### ISSUE TITLE
DEADCODE in function 'spdm_test_case_algorithms_unexpected_request'

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/SPDM-Responder-Validator#18]
Line 532 `version = 0`, the value of `version` has not changed.
Line 543 and 550 are not executed
https://github.com/DMTF/SPDM-Responder-Validator/blob/61debbcffb1cd240f2908aee95ead1a974272322/library/spdm_responder_conformance_test_lib/spdm_responder_test_3_algorithms.c#L530-L551
same issue
https://github.com/DMTF/SPDM-Responder-Validator/blob/61debbcffb1cd240f2908aee95ead1a974272322/library/spdm_responder_conformance_test_lib/spdm_responder_test_3_algorithms.c#L562-L566
same issue
https://github.com/DMTF/SPDM-Responder-Validator/blob/61debbcffb1cd240f2908aee95ead1a974272322/library/spdm_responder_conformance_test_lib/spdm_responder_test_3_algorithms.c#L573-L575
same issue
https://github.com/DMTF/SPDM-Responder-Validator/blob/61debbcffb1cd240f2908aee95ead1a974272322/library/spdm_responder_conformance_test_lib/spdm_responder_test_3_algorithms.c#L586-L588
same issue
https://github.com/DMTF/SPDM-Responder-Validator/blob/61debbcffb1cd240f2908aee95ead1a974272322/library/spdm_responder_conformance_test_lib/spdm_responder_test_3_algorithms.c#L594-L597
same issue
https://github.com/DMTF/SPDM-Responder-Validator/blob/61debbcffb1cd240f2908aee95ead1a974272322/library/spdm_responder_conformance_test_lib/spdm_responder_test_3_algorithms.c#L618-L623

**Comment by jyao1** [comment]
test_buffer->version should be used.
