### ISSUE TITLE
Altering SPDM Context Leaks to Subsequent Tests

### ISSUE THREAD

**Issue by mct-sparky** [DMTF/SPDM-Responder-Validator#24]
The same SPDM context is shared amongst the test suite. This means any alterations that aren't torn down are leaked to subsequent tests. This issue manifests in the following example:

1. Responder Under Test supports SPDM Version 1.1
2. Setup function spdm_test_case_capabilities_setup_version_10, called, changing requester version to 1.0
3. Setup fails due to version mismatch in libspdm_get_version.
4. Next test calls spdm_test_case_capabilities_setup_version_all, which does not alter requester version, meaning setup will fail again due to version mismatch. 

Had the step 2. been reverted or not leaked, step 4. would have passed. 

https://github.com/DMTF/SPDM-Responder-Validator/blob/5ae6af6e38c2a902d144dd22218952766b095287/library/spdm_responder_conformance_test_lib/spdm_responder_test_2_capabilities.c#L17-L46

This is happening anywhere ..._setup_version_XX is called.

**Comment by jyao1** [comment]
I think we need add init in every case setup function and deinit in every case teardown function.
