### ISSUE TITLE
Timestamp for measurement

### ISSUE THREAD

**Issue by rupesh-hpe** [DMTF/SPDM-Responder-Validator#28]
https://github.com/DMTF/SPDM-Responder-Validator/blob/5ae6af6e38c2a902d144dd22218952766b095287/doc/7.Measurements.md 

The measurement should have a time stamp field to indicate when the measurement was done.

**Comment by jyao1** [comment]
I am confused here. SPDM spec does not mention time-stamp.

Are you asking feature request for SPDM specification? If so, please file an issue in SPDM-WG not here.
