### ISSUE TITLE
Newbie for SPDM responder validator

### ISSUE THREAD

**Issue by goutham23** [DMTF/SPDM-Responder-Validator#39]
Hello,
I've implemented the responder code and my path is SPDM over MCTP over PCIe. I'm planning to use SPDM-responder-validator code to test my implementation.

1)Is there a document that talks about setting up the test code, like compiling, loading, or setting the configuration to talk to the correct responder?
2) I have a setup, PCIe card (storage controller), and have both WINOS and LINUX OS, which OS do you recommend to plugin SPDM-responder-validator? 
3)I read that SPDM-responder-validator supports SPDM over MCTP over PCIe - correct?
4) SPDM requester emulator is the code we need to refer to get SPDM responder validator done, is that correct?

Overall I'm looking for guidance to plugin SPDM-responder-validator and establish the connection with the responder

Please Advise

**Comment by steven-bellock** [comment]
This was discussed at the Monday meeting. @goutham23 if you feel all the questions have been answered please close this issue.
