### ISSUE TITLE
Checking for heartbeat interval while testing end_session_ack with validator (test 16)

### ISSUE THREAD

**Issue by PavelPu123** [DMTF/SPDM-Responder-Validator#62]
Hello
I'm not sure I understand the logic of checking the heartbeat interval in spdm_test_case_end_session_ack_setup_session (line 164):

https://github.com/DMTF/SPDM-Responder-Validator/blob/d2451d8533fff6b0249484a4b9bf52705f73e948/library/spdm_responder_conformance_test_lib/spdm_responder_test_16_end_session_ack.c#L164-L166

This check affects the specific test since it's not a requirement to setup the heartbeat interval in responder as part of this test.

Thanks in advance for your comments.

**Comment by jyao1** [comment]
I think it is copy-paste error. It should be removed. Good catch!
