### ISSUE TITLE
Validator skips libspdm_zero_mem(&parameter) if spdm_version_count ==0

### ISSUE THREAD

**Issue by oferhz** [DMTF/SPDM-Responder-Validator#69]
Any reason the "parameter" field is not erased before fields are set via libspdm_set_data?
Couldn't garbage in this parameter have negative effect on the Validator run?

**Comment by jyao1** [comment]
Could you point out which line of code your are referring to?

**Comment by oferhz** [comment]
For example `spdm_test_case_certificate_setup_vca_digest`, it receives the `spdm_version_number_t *spdm_version` as a parameter and upon it`s value decides if to memzero the `libspdm_data_parameter_t parameter`.

**Comment by oferhz** [comment]
at least on my i64 machine I see that `parameter.location` field is sometimes `1` and sometimes `2` when `spdm_version == 0`, the `libspdm_set_data` assumes this field is set correctly and acts accordingly.
