### ISSUE TITLE
[bug?] spdm_responder_test_7_measurements: assert mismatch

### ISSUE THREAD

**Issue by twilfredo** [DMTF/SPDM-Responder-Validator#73]
Hey all,

When running the tests I noticed an assert fail (dead loop), on https://github.com/DMTF/SPDM-Responder-Validator/blob/e3bc88c1d635a68de167dabceb884ba94626485b/library/spdm_responder_conformance_test_lib/spdm_responder_test_7_measurements.c#L1682

and here too (although this one doesn't fail the assertion) https://github.com/DMTF/SPDM-Responder-Validator/blob/e3bc88c1d635a68de167dabceb884ba94626485b/library/spdm_responder_conformance_test_lib/spdm_responder_test_7_measurements.c#L1449

Should this assert be instead    ` LIBSPDM_ASSERT(spdm_test_context->test_scratch_buffer_size == sizeof(*test_buffer));`

The assert works with this change, I couldn't quite figure out why we are comparing it to the version field. Is this assert even required?

Update: 

Some other places where this assertion failed:

https://github.com/DMTF/SPDM-Responder-Validator/blob/e3bc88c1d635a68de167dabceb884ba94626485b/library/spdm_responder_conformance_test_lib/spdm_responder_test_8_key_exchange_rsp.c#L1042

https://github.com/DMTF/SPDM-Responder-Validator/blob/e3bc88c1d635a68de167dabceb884ba94626485b/library/spdm_responder_conformance_test_lib/spdm_responder_test_9_finish_rsp.c#L853

Thanks

**Comment by steven-bellock** [comment]
@twilfredo Are you bringing in the current libspdm `main` branch into this repository, or using the synced version of libspdm?

**Comment by twilfredo** [comment]
> @twilfredo Are you bringing in the current libspdm `main` branch into this repository, or using the synced version of libspdm?

Hey @steven-bellock ,

We are using libspdm@2.3.1 release and the only commit of `SPDM-Responder-Validator` that I found runs the tests properly (so far), was 1dc130e52f94c2419e8bdb4918f6969b421d2eac.

**Comment by jyao1** [comment]
@twilfredo , if you are using `libspdm@2.3.1`, would you please try the SPDM-Responder-Validator in `spdm-emu@2.3.1` ?
It is a submodule of spdm-emu.

**Comment by twilfredo** [comment]
> @twilfredo , if you are using `libspdm@2.3.1`, would you please try the SPDM-Responder-Validator in `spdm-emu@2.3.1` ? It is a submodule of spdm-emu.

Thanks for the response! I just tried this, `spdm-emu@2.3.1` points to SPDM-Responder-Validator@c5a3b5b9. I'm seeing the same assert failures (built in debug mode, so goes into the infinite loop). Do those asserts look correct to you?

**Comment by twilfredo** [comment]
ping!

**Comment by Wenxing-hou** [comment]
I am checking it. Thanks.

**Comment by twilfredo** [comment]
> I am checking it. Thanks.

Great, thanks!

**Comment by Wenxing-hou** [comment]
The assert mismatch is indeed a bug. And the PR is submitted to fix it. Thanks

**Comment by twilfredo** [comment]
> The assert mismatch is indeed a bug. And the PR is submitted to fix it. Thanks

great, thanks!
