### ISSUE TITLE
Undefined behavior

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/SPDM-Responder-Validator#76]
Many tests use the pattern https://github.com/DMTF/SPDM-Responder-Validator/blob/f83abe7cf7d5fbaa30b963bd321bca069e294eb8/library/spdm_responder_conformance_test_lib/spdm_responder_test_7_measurements.c#L1578-L1586 when searching for invalid slot IDs. `test_buffer->slot_mask` and `slot_id` are both `uint8_t`s. If `slot_id` is greater than `7` then the left-shift invokes undefined behavior.

**Comment by jyao1** [comment]
From the code logic, if `(slot_id < SPDM_MAX_SLOT_COUNT)` is false, the `(0x1 << slot_id)` wont be executed.

**Comment by jyao1** [comment]
We agree to close it at this moment. If we have real issue later, we can open that.
