### ISSUE TITLE
test alg_count in Case 3.4

### ISSUE THREAD

**Issue by lazineer** [DMTF/SPDM-Responder-Validator#78]
Since FixedAlgCount should be 2, I think `alg_count` should be 0x2F.

https://github.com/DMTF/SPDM-Responder-Validator/blob/132846019ad4847873b6b7b69c717a048465eace/library/spdm_responder_conformance_test_lib/spdm_responder_test_3_algorithms.c#L862-L865

**Comment by jyao1** [comment]
The purpose is to test invalid count. 0x0F is invalid. Why we need 0x2F ?

**Comment by lazineer** [comment]
Isn't the purpose of testing for invalid ExtAlgCount? Then, I think 0x2F would be correct to test without being affected by FixedAlgCount.

**Comment by lazineer** [comment]
If AlgCount is 0x0F, FixedAlgCount is 0x0 and ExtAlgCount is 0xF. Both FixedAlgCount and ExtAlgCount are invalid values. What I mean is that FixedAlgCount needs to be 0x2 to test ExtAlgCount. The [test doc](https://github.com/DMTF/SPDM-Responder-Validator/blob/main/doc/3.Algorithms.md) also says "ExtAlgCount_0=0xF, ExtAlgCount_1=0xF".
I think it is better to separate the case where AlgCount is 0x0F into the case where AlgCount is 0x0 and the case where AlgCount is 0x2F.

**Comment by Wenxing-hou** [comment]
> If AlgCount is 0x0F, FixedAlgCount is 0x0 and ExtAlgCount is 0xF. Both FixedAlgCount and ExtAlgCount are invalid values. What I mean is that FixedAlgCount needs to be 0x2 to test ExtAlgCount. The [test doc](https://github.com/DMTF/SPDM-Responder-Validator/blob/main/doc/3.Algorithms.md) also says "ExtAlgCount_0=0xF, ExtAlgCount_1=0xF". I think it is better to separate the case where AlgCount is 0x0F into the case where AlgCount is 0x0 and the case where AlgCount is 0x2F.

Thanks. I have changed 0x0F to 0x2F.

For your adding "AlgCount is 0x0" case suggestion, I think the origin code has the case:
https://github.com/DMTF/SPDM-Responder-Validator/blob/6a4ee45c4f02bd39b2f4b06a21c419d46a0ea18d/library/spdm_responder_conformance_test_lib/spdm_responder_test_3_algorithms.c#L842-L857
