### ISSUE TITLE
Need to check `Case 9.6` in `9.FinishRsp`

### ISSUE THREAD

**Issue by lazineer** [DMTF/SPDM-Responder-Validator#89]
According to [Table 61 - FINISH request message format, DSP0274](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf), `Param2` is reserved, if `Param1` is not set.

`Param2` is descrived like below.
> SlotID. Only valid if Param1 = 0x01, otherwise reserved.

In [Case 9.6](https://github.com/DMTF/SPDM-Responder-Validator/blob/main/doc/9.FinishRsp.md#case-96-1), I think it needs to change the 'Param1.Sig' from `0` to `1` to get `InvalidRequest`. If `Param1.sig` is `0` like Case 9.6 currently, I think the responder has to response a correct `FINISH_RSP`.

Could you check what I wrote above?

**Comment by lazineer** [comment]
There are two Case 9.6 in 9.FinishRsp. What you mentioned is next to Case 9.3. It has incorrect number. What I mentioned is "Description: SPDM responder shall return ERROR(InvalidRequest), if it receives a FINISH with invalid field." and it is next to Case 9.5.

**Comment by jyao1** [comment]
Ah, I think you are right.
