### ISSUE TITLE
remove the measurement summary hash check for SPDM 1.0 and 1.1

### ISSUE THREAD

**Issue by jyao1** [DMTF/SPDM-Responder-Validator#99]
The text in SPDM 1.0 and 1.1 is confusing.

Only SPDM 1.2 defines the behavior precisely.

See https://github.com/DMTF/libspdm/issues/2404

**Comment by mcsmonk** [comment]
I think it is better that https://github.com/DMTF/libspdm/issues/2404#issuecomment-1760456758 instead of removing this check
